language: python
python: 3.6
branches: master
install:
- pip install mkdocs mkdocs-material
script: true
before_deploy:
- mkdocs build --verbose --clean
deploy:
  edge: true
  provider: pages
  skip_cleanup: true
  local_dir: site
  github_token:
      secure: "jdREY/BkynxSh03nac2+z72jx+TNrryLvd3Bw7VF7KFOKY//0Y3SX7H7GSjRCTfMJgT7b7Z5IwS5PrwwnPh8YEEroUhHkLqGnpvjWLxL4Sb1iMHq7sNZVtIlxs+oUREVfY0br2cFfYJvkBYRh9Y2OEwXfXwxRXiD6dgVkUhu0z2SbZv92pr/DxCEW8XJdUOCWc/T8j6b7XUZQfhckmc8NPlK5qPKN6TUBstGxdXhVfzeDRSXICah6EHXpCUNsmx1p64zYCFcU1uOrmR3dR+iE5T9tbslrE8N00G30D9jaEtimp/NmwbiPh8PoJwCCHPuOSwhaATa3w6S69EbqTNd5oauk6enMyqlVD4sOWFbCf9jswTE3nnbeIvUjCPEzID84Eanj52KGMeUbEHcPhYUNp5JPXljvoF7s8qzT/moG+VcLoTWwCMQT8Wd6SrokxoPXEQrgCfjDCriDktZQx1uELrnssjECOPDBb4lsdC74m3uwsszgXOBDC/SP1CpxF5DYvgfCk0UZ7aK3hq9pgyHdRvhIZou1gUSFlaPtxzbRZ3qK9X7rynDOfT7D3F5ScIy5hdG0FZw7TRU/8g+3ok4pygmnnTB8pKJaDbAjNsx5ItIj3hC0mzB4aqIo81uoblvF/DOckBF3BkyHtNfo1MlfNIZp98ciGqLVenYX0yAmR4="
  on:
    branch: master
